#! /bin/sh
# /etc/init.d/servoblaster 

### BEGIN INIT INFO
# Provides:          servoblaster
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Startup script for ServoBlaster daemon
# Description:       A simple script for the Hexapod project that will start / stop the ServoBlaster Daemon
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting servoblaster daemon"
    /home/pi/hexapod/Rpi/ServoBlaster/user/servod --p1pins="15,13,12,19,21,22,23,24,26,29,31,32,33,35,36,37,38,40"
    ;;
  stop)
    echo "Stopping servoblaster daemon"
    killall servod
    ;;
  *)
    echo "Usage: /etc/init.d/servoblaster {start|stop}"
    exit 1
    ;;
esac

exit 0
